services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - '5434:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Utiliser un volume pour persister les données
    restart: always  # Redémarrer le conteneur en cas de problème
  adminer:
    image: adminer
    restart: always
    ports:
      - '9080:8080'